# Generated by Django 2.1.5 on 2019-02-27 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_blog_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='food',
        ),
    ]
