# Generated by Django 2.1.5 on 2019-02-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='food',
            field=models.CharField(choices=[('^_^', '^_^'), ('breakfast', 'BREAKFAST'), ('lunch', 'LUNCH'), ('dinner', 'DINNER'), ('snacks', 'SNACKS')], default='^_^', max_length=9),
        ),
    ]
