# Generated by Django 2.1.5 on 2019-02-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0004_auto_20190227_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='calorie',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
