# Generated by Django 2.1.5 on 2019-03-01 11:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 1, 11, 55, 29, 694660, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
