# Generated by Django 2.1.5 on 2019-03-01 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolio_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='pub_date',
        ),
    ]
